### ISSUE TITLE
Revise "editorial" to "publisher" 

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015_books#23]
It's the most correct way of doing it.

**Comment by unintendedbear** [comment]
I've been reviewing where the "editorial" or "editor" words are and I found two main problems:
- In "Trevenque Editorial S.L.", that I guess is the Spanish name so it should remain as it is (because in Spanish it indeed is "Editorial").
- You named a parameter/feature "editorial". This is inconsistent with everything else I'm changing and I think is the reason why @7ossam81 said this morning that the two words are used in the paper.

So, what can we do? :(

**Comment by JJ** [comment]
2016-04-28 14:07 GMT+02:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> I've been reviewing where the "editorial" or "editor" words are and I
> found two main problems:
> - In "Trevenque Editorial S.L.", that I guess is the Spanish name so
>   it should remain as it is (because in Spanish it indeed is "Editorial").
> 
> That's OK
> - You named a parameter/feature "editorial". This is inconsistent with
>   everything else I'm changing and I think is the reason why @7ossam81
>   https://github.com/7ossam81 said this morning that the two words are
>   used in the paper.
> 
> So, what can we do? :(

If that word is not in the figures, change it. And if it is in figures,
change the figures...

JJ

**Comment by unintendedbear** [comment]
Ok :D

**Comment by unintendedbear** [comment]
Re-assigning to @7ossam81 for review. I'm going to review the whole paper, anyways :)
