### ISSUE TITLE
Discussion about sections 3 and 4

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2015_books#29]
Hi all,

there are a lot of comments suggesting that content in section 4.1 should be placed in section 3.
Actually, I was improving section 4 this morning and one of my goals was to reference 4.1, 4.2 and 4.3 in the description of the methodology at the beginning of the section. However, the description talks about preprocessing (4.2), data collection (4.1) and method selection (4.3), in this order (not the correct one, of course).

So, what do you think? 

Also, **please** review comments and erase those already addressed :(

**Comment by JJ** [comment]
Now Section 3 has only a few paragraphs. It should be moved to Introduction, I think, if it's left that way. Adding 4.1 would make it better probably. The intro to that section should be moved further down the paper, no sense to talk about measures at that point.

**Comment by 7ossam81** [comment]
I think a small subsection could be added to section 4 to wrap up the evaluation measures and reflects the fourths step "Evaluation" in the KDD process. What do you think ?

**Comment by JJ** [comment]
Do it, by all means.

**Comment by amorag** [comment]
Hi,

I think that a section talking about the problem to address is necessary in a paper.
Now it is not just a couple of paragraphs, it also includes Table 1.
However I think that this section should be improved and completed somehow, in order to become really interesting/important for the paper.

For instance @JJ (who has a vast knowledge about this ;D) could comment the difficulties of this type of problem from the point of view of the variability of the market, the seasonality, fashions and their influence, or something in this line. ;)

In my opinion, Section 4 is correctly structured as it is (collection, preprocessing/FS, forecasting) and I agree in adding a section about evaluation.
I also agree in improving the introduction of Section 4 and moving the error measures to section 4.3 of to new section 4.4 (evaluation).
