### ISSUE TITLE
Try to better justify the use of PRINT-RUN as an input

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2015_books#39]
Please, check the text where it is referenced now and include any additional justification you think could be acceptable. ;)

**Comment by pacastillo** [comment]
I have reviewed the text, fixing some 'typos' and making much clear some sentences.

I have made clear along the text the main objective of the paper: 

"we are tackling the problem of predicting total sales in order to print the right amount of books" (abstract)

and justified the use of that set of input variables (lines 399 to 404):

"On the other hand, print_run has been considered as an input variable because it is something to be decided in advance by a publisher. [...] the publisher can try different values for it and see what the predictor yields, in order to take the best decision."
